# Generated by Django 4.0.2 on 2022-03-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Sex', models.CharField(default='M', max_length=2)),
                ('Birth', models.DateField()),
                ('Email', models.CharField(blank=True, default='', max_length=100)),
                ('Phone', models.CharField(blank=True, default='', max_length=50)),
                ('home_Address', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
